"""The skill router: a live CRDT skill (`skill-router`) that fires at the start
of every task, carrying live-editable routing rules plus an auto-generated index
of every skill in the library.

The index is regenerated by walking the static library (catalog/ + authored/) and
the live-skill store, then patched into the router doc between INDEX markers — the
*only* region a rebuild touches, so hand edits to the rules above it are preserved
("live-edit after seed"). Because the router is an ordinary live skill it rides the
existing skilldoc sync mesh: regenerate on the owner, every peer's file updates.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from pathlib import Path

from devtools_mcp.skilldocs import store as store_mod
from devtools_mcp.skilldocs import variants
from devtools_mcp.skills_discovery import find_skills_root

ROUTER_NAME: str = "skill-router"
CONTROL_DOC: str = "skill-control"  # reserved: never materialized as a loadable skill
INDEX_START: str = "<!-- INDEX:START (generated — do not edit; rebuilt by skill_live action=route) -->"
INDEX_END: str = "<!-- INDEX:END -->"
DESC_MAX: int = 200  # chars of each skill description shown in the index
FRONTMATTER_SCAN_LINES: int = 60
_BLOCK_SCALARS = {">", "|", ">-", "|-", ">+", "|+"}

_GOAP_RE = re.compile(r"^```goap[ \t]*\r?\n(.*?)\r?\n```[ \t]*$", re.MULTILINE | re.DOTALL)


@dataclass(frozen=True)
class Entry:
    """One skill in the index."""

    name: str
    description: str
    category: str
    modes: list[str] = field(default_factory=list)  # variant power levels, if any
    goap: dict | None = None  # parsed ```goap descriptor (preconditions/effects/cost)

    @property
    def has_goap(self) -> bool:
        return self.goap is not None


# -- parsing ------------------------------------------------------------------


def read_frontmatter(content: str) -> tuple[str, str] | None:
    """(name, description) from a SKILL.md string; None if not a valid skill.

    Handles folded/block `description: >` values (PyYAML is not a dependency).
    """
    assert isinstance(content, str), "content must be str"
    lines = content.splitlines()
    if not lines or lines[0].strip() != "---":
        return None
    name = ""
    desc_parts: list[str] = []
    in_desc = False
    for line in lines[1:FRONTMATTER_SCAN_LINES]:  # bounded
        if line.strip() == "---":
            break
        if in_desc:
            if line and not line[0].isspace():
                in_desc = False  # dedented → a new key; fall through to parse it
            else:
                if line.strip():
                    desc_parts.append(line.strip())
                continue
        if line.startswith("name:"):
            name = line.split(":", 1)[1].strip().strip("'\"")
        elif line.startswith("description:"):
            rest = line.split(":", 1)[1].strip()
            if rest in _BLOCK_SCALARS or not rest:
                in_desc = True
            else:
                desc_parts.append(rest.strip("'\""))
    if not name:
        return None
    return name, " ".join(desc_parts).strip()


def parse_goap(content: str) -> dict | None:
    """The first ```goap fenced JSON block as a dict, or None."""
    assert isinstance(content, str), "content must be str"
    match = _GOAP_RE.search(content)
    if not match:
        return None
    try:
        data = json.loads(match.group(1))
    except json.JSONDecodeError:
        return None
    return data if isinstance(data, dict) else None


def _entry_from(content: str, category: str) -> Entry | None:
    parsed = read_frontmatter(content)
    if parsed is None:
        return None
    name, description = parsed
    if len(description) > DESC_MAX:
        description = description[: DESC_MAX - 1].rstrip() + "…"
    return Entry(
        name=name,
        description=description,
        category=category,
        modes=variants.detect_modes(content),
        goap=parse_goap(content),
    )


# -- collection ---------------------------------------------------------------


def _collect_tree(tree: Path) -> list[Entry]:
    """Entries from a category-nested source tree (catalog/ or authored/)."""
    out: list[Entry] = []
    if not tree.is_dir():
        return out
    for md in sorted(tree.rglob("SKILL.md"))[:store_mod.SKILLS_MAX]:  # bounded
        rel = md.relative_to(tree)
        # Skip sidelined categories (experimental / _archive) — harvested for
        # reference but not synced to mirrors, so not loadable; keep them out of
        # the index which advertises only loadable skills.
        if any(seg == "experimental" or seg.startswith("_") for seg in rel.parts[:-2]):
            continue
        category = rel.parts[0] if len(rel.parts) > 1 else "uncategorized"
        try:
            content = md.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        entry = _entry_from(content, category)
        if entry is not None:
            out.append(entry)
    return out


def collect_skills(store: store_mod.SkillDocStore) -> list[Entry]:
    """Every indexable skill: static library (catalog + authored) + live skills.

    Deduplicated by name (authored wins over catalog, live is listed separately).
    Names in the SkillControl disabled set are pruned — static or live — so
    irrelevant skills (e.g. build tools for languages a machine never touches)
    can be removed from the router without deleting them anywhere.
    """
    from devtools_mcp.skilldocs.control import SkillControl

    control = SkillControl(conn=store.conn)
    disabled = control.disabled()
    root = find_skills_root()
    by_name: dict[str, Entry] = {}
    if root is not None:
        for entry in _collect_tree(root / "catalog" / "skills"):
            by_name[entry.name] = entry
        for entry in _collect_tree(root / "authored" / "skills"):
            by_name[entry.name] = entry  # authored overrides catalog on name clash
    for meta in store.list_skills():  # bounded by SKILLS_MAX
        name = meta["name"]
        if name in (ROUTER_NAME, CONTROL_DOC):
            continue
        try:
            content = store.get_text(name)
        except store_mod.SkillDocError:
            continue
        entry = _entry_from(content, "live")
        if entry is not None:
            by_name[name] = entry
    entries = sorted(
        (e for e in by_name.values() if e.name not in disabled), key=lambda e: (e.category, e.name)
    )
    assert len(entries) <= store_mod.SKILLS_MAX, "index size exceeded bound"
    return entries


# -- rendering ----------------------------------------------------------------


def build_index(entries: list[Entry], mode: str) -> str:
    """Deterministic marker-delimited index, grouped by category."""
    assert isinstance(mode, str) and mode, "mode required"
    lines = [INDEX_START, "", f"## Available skills ({len(entries)}) — active power mode: **{mode}**", ""]
    current = None
    for entry in entries:
        if entry.category != current:
            current = entry.category
            lines.append(f"### {current}")
        tags = []
        if entry.modes:
            tags.append("power: " + "/".join(entry.modes))
        if entry.has_goap:
            tags.append("goap")
        suffix = f"  _({'; '.join(tags)})_" if tags else ""
        lines.append(f"- **{entry.name}** — {entry.description}{suffix}")
    lines.extend(["", INDEX_END])
    return "\n".join(lines)


def _default_rules() -> str:
    return (
        "# Skill Router\n\n"
        "At the start of a task, scan the index below and load the skill whose "
        "description matches the work. Prefer a specific skill over improvising. "
        "If several fit, pick the most specific; if none fit, proceed without one. "
        "For a multi-step goal, a planner (when configured) can sequence skills — "
        "otherwise dispatch one skill at a time from the index.\n\n"
        "_Rules above are live-editable; the index below is regenerated._\n"
    )


def _load_rules() -> str:
    root = find_skills_root()
    if root is not None:
        rules_file = root / "authored" / "skills" / "meta" / "skill-router.rules.md"
        if rules_file.is_file():
            text = rules_file.read_text(encoding="utf-8", errors="replace").strip()
            if text:
                return text + "\n"
    return _default_rules()


def _router_doc(rules: str, index: str, mode: str) -> str:
    description = (
        "Skill router — consult at the START OF EVERY TASK to find the right skill "
        "for the work. Indexes every available skill with its trigger; states the "
        "active power mode. Load this first, then load the matched skill."
    )
    return f"---\nname: {ROUTER_NAME}\ndescription: >\n  {description}\n---\n\n{rules}\n{index}\n"


# -- rebuild ------------------------------------------------------------------


def rebuild(store: store_mod.SkillDocStore, mode: str | None = None) -> Path | None:
    """Create or refresh the `skill-router` live skill. Patches only the index
    block on an existing router (rules preserved). Returns the materialized path.
    """
    if mode is None:
        from devtools_mcp.skilldocs.control import SkillControl

        control = SkillControl()
        try:
            mode = control.global_mode()
        finally:
            control.close()
    entries = collect_skills(store)
    index = build_index(entries, mode)
    if not store.exists(ROUTER_NAME):
        return store.create(ROUTER_NAME, _router_doc(_load_rules(), index, mode))
    current = store.get_text(ROUTER_NAME)
    start = current.find(INDEX_START)
    end = current.find(INDEX_END)
    if start == -1 or end == -1:  # legacy router without markers: append a block
        return store.append(ROUTER_NAME, "\n\n" + index)
    old_block = current[start : end + len(INDEX_END)]
    if old_block == index:
        return store_mod.publish_root() / ROUTER_NAME / "SKILL.md"  # already current
    return store.patch(ROUTER_NAME, old_block, index)
